import { useState, useRef } from "react";
import axios from "axios";
import { useNavigate } from "react-router-dom";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { jwtDecode } from "jwt-decode";

function SalesReport() {

    const navigate = useNavigate();

    const [startDate, setStartDate] = useState("");
    const [endDate, setEndDate] = useState("");

    const [sales, setSales] = useState([]);

    const listRef = useRef(null);

    const scrollToTop = () => {
        listRef.current?.scrollTo({
            top: 0,
            behavior: "smooth"
        });
    };

    // =========================
    // FORMAT DATE & TIME
    // =========================
    const formatDateTime = (dateString) => {

        if (!dateString) return "N/A";

        const date = new Date(dateString);

        return date.toLocaleString("en-GB", {
            year: "numeric",
            month: "2-digit",
            day: "2-digit",
            hour: "2-digit",
            minute: "2-digit",
            second: "2-digit"
        });
    };

    // =========================
    // FETCH SALES
    // =========================
    const fetchSales = async () => {

        if (!startDate || !endDate) {
            alert("Please select both dates");
            return;
        }

        try {

            const token = localStorage.getItem("token");

            const res = await axios.get(
                `http://localhost:8080/api/sales/by-date-range?startDate=${startDate}&endDate=${endDate}`,
                {
                    headers: {
                        Authorization: `Bearer ${token}`
                    }
                }
            );

            setSales(res.data);

            scrollToTop();

        } catch (err) {
            alert(err.response?.data?.message || "Failed to load sales");
        }
    };

    // =========================
    // TOTALS
    // =========================
    const cashTotal = sales
        .filter((s) => s.paymentMethod === "CASH")
        .reduce((sum, s) => sum + s.totalAmount, 0);

    const mpesaTotal = sales
        .filter((s) => s.paymentMethod === "MPESA")
        .reduce((sum, s) => sum + s.totalAmount, 0);

    const grandTotal = sales.reduce(
        (sum, s) => sum + s.totalAmount,
        0
    );

    // =========================
    // PDF DOWNLOAD
    // =========================
    const downloadPDF = () => {

        if (sales.length === 0) {
            alert("Please select sales period");
            return;
        }

        const token = localStorage.getItem("token");

        let loggedInUser = "Unknown User";

        if (token) {

            try {

                const decoded = jwtDecode(token);

                loggedInUser =
                    decoded.sub ||
                    decoded.username ||
                    decoded.email ||
                    "Unknown User";

            } catch (error) {
                console.error("Invalid token");
            }
        }

        const doc = new jsPDF("landscape");

        const generatedAt = new Date().toLocaleString();

        const formatMoney = (value) => {

            return Number(value || 0).toLocaleString(
                "en-US",
                {
                    minimumFractionDigits: 2,
                    maximumFractionDigits: 2
                }
            );
        };

        const pageWidth = doc.internal.pageSize.width;
        const rightX = pageWidth - 14;

        const topY = 20;

        doc.setFontSize(18);
        doc.setFont(undefined, "bold");
        doc.text("SALES REPORT", 14, topY);

        doc.setFontSize(18);
        doc.setFont(undefined, "bold");
        doc.text("SALES SUMMARY", rightX - 60, topY);

        doc.setFontSize(11);
        doc.setFont(undefined, "normal");

        doc.text(
            `Report Period: ${startDate} to ${endDate}`,
            14,
            30
        );

        doc.text(
            `Generated By: ${loggedInUser}`,
            14,
            38
        );

        doc.text(
            `Generated At: ${generatedAt}`,
            14,
            46
        );

        doc.setFontSize(11);

        doc.setFont(undefined, "bold");

        doc.text("CASH:", rightX - 80, 30);

        doc.text(
            `KES ${formatMoney(cashTotal)}`,
            rightX,
            30,
            { align: "right" }
        );

        doc.text("MPESA:", rightX - 80, 38);

        doc.text(
            `KES ${formatMoney(mpesaTotal)}`,
            rightX,
            38,
            { align: "right" }
        );

        doc.text("GRAND TOTAL:", rightX - 80, 46);

        doc.text(
            `KES ${formatMoney(grandTotal)}`,
            rightX,
            46,
            { align: "right" }
        );

        doc.setFont(undefined, "normal");

        doc.setFontSize(14);

        doc.text("Sales Details", 14, 60);

        const tableRows = [];

        sales.forEach((sale) => {

            sale.items.forEach((item) => {

                tableRows.push([
                    sale.id,
                    item.productName,
                    item.quantity,
                    `KES ${formatMoney(item.price)}`,
                    `KES ${formatMoney(item.subtotal)}`,
                    sale.paymentMethod,
                    sale.cashierName || "Unknown",
                    formatDateTime(sale.createdAt)
                ]);

            });

        });

        autoTable(doc, {
            startY: 68,

            head: [[
                "Sale ID",
                "Product Name",
                "Quantity",
                "Price",
                "Subtotal",
                "Payment Method",
                "Sold By",
                "Sale Date & Time"
            ]],

            body: tableRows,

            styles: {
                fontSize: 9
            },

            headStyles: {
                fillColor: [41, 128, 185]
            }
        });

        const pageCount =
            doc.internal.getNumberOfPages();

        for (let i = 1; i <= pageCount; i++) {

            doc.setPage(i);

            doc.setFontSize(10);

            doc.text(
                `Generated by ${loggedInUser} on ${generatedAt}`,
                14,
                doc.internal.pageSize.height - 10
            );

            doc.text(
                `Page ${i} of ${pageCount}`,
                doc.internal.pageSize.width - 40,
                doc.internal.pageSize.height - 10
            );
        }

        doc.save(
            `Sales_Report_${startDate}_to_${endDate}.pdf`
        );
    };

    return (

        <div className="p-6 bg-gray-100 h-screen flex flex-col">

            <h1 className="text-3xl font-bold mb-4">
                Manager Sales Report
            </h1>

            {/* FILTERS */}
            <div className="flex flex-wrap gap-3 mb-4">

                <input
                    type="date"
                    value={startDate}
                    onChange={(e) =>
                        setStartDate(e.target.value)
                    }
                    className="border p-3 rounded-lg"
                />

                <input
                    type="date"
                    value={endDate}
                    onChange={(e) =>
                        setEndDate(e.target.value)
                    }
                    className="border p-3 rounded-lg"
                />

                <button
                    onClick={fetchSales}
                    className="bg-blue-600 hover:bg-blue-700 text-white px-6 rounded-lg"
                >
                    Load Sales
                </button>

                <button
                    onClick={downloadPDF}
                    className="bg-green-600 hover:bg-green-700 text-white px-6 rounded-lg"
                >
                    Download Sales Report
                </button>

            </div>

            {/* SUMMARY */}
            <div className="bg-white p-4 rounded-xl shadow mb-4 sticky top-0 z-10">

                <div className="grid grid-cols-3 text-center">

                    <div className="text-green-600 font-bold">
                        CASH: KES {cashTotal.toFixed(2)}
                    </div>

                    <div className="text-blue-600 font-bold">
                        MPESA: KES {mpesaTotal.toFixed(2)}
                    </div>

                    <div className="text-black font-bold">
                        GRAND: KES {grandTotal.toFixed(2)}
                    </div>

                </div>

            </div>

            {/* MAIN CONTENT */}
            <div className="flex flex-1 gap-6 overflow-hidden">

                {/* SALES LIST */}
                <div
                    ref={listRef}
                    className="w-1/3 bg-white p-5 rounded-xl shadow-lg overflow-y-auto"
                >

                    <h2 className="text-xl font-bold mb-4">
                        Sales History
                    </h2>

                    {sales.length === 0 ? (

                        <p className="text-gray-500">
                            No sales found
                        </p>

                    ) : (

                        sales.map((sale) => (

                            <div
                                key={sale.id}
                                className="border rounded-lg p-4 mb-3 bg-gray-50"
                            >

                                <div className="flex justify-between items-center">

                                    <p className="font-bold">
                                        Sale #{sale.id}
                                    </p>

                                    <span
                                        className={`px-3 py-1 rounded-full text-sm font-bold
                                        ${sale.paymentMethod === "CASH"
                                                ? "bg-green-100 text-green-700"
                                                : "bg-blue-100 text-blue-700"
                                            }`}
                                    >
                                        {sale.paymentMethod}
                                    </span>

                                </div>

                                <p className="mt-2">
                                    Sold By: {sale.cashierName}
                                </p>

                                <p className="text-sm text-gray-600">
                                    Date & Time:{" "}
                                    {formatDateTime(sale.createdAt)}
                                </p>

                                <p className="font-bold mt-2">
                                    Total: KES {sale.totalAmount}
                                </p>

                            </div>

                        ))

                    )}

                </div>

                {/* ALL SALE ITEMS */}
                <div className="w-2/3 bg-white p-5 rounded-xl shadow-lg overflow-y-auto">

                    <h2 className="text-xl font-bold mb-4">
                        All Sale Items
                    </h2>

                    {sales.length === 0 ? (

                        <p className="text-gray-500">
                            No sale items found
                        </p>

                    ) : (

                        <div className="space-y-6">

                            {sales.map((sale) => (

                                <div
                                    key={sale.id}
                                    className="border rounded-xl overflow-hidden"
                                >

                                    {/* SALE HEADER */}
                                    <div className="bg-gray-100 p-3 border-b">

                                        <div className="flex justify-between flex-wrap">

                                            <div>

                                                <div className="flex items-center gap-3">

                                                    <p className="font-bold">
                                                        Sale #{sale.id}
                                                    </p>

                                                    <span
                                                        className={`px-3 py-1 rounded-full text-sm font-bold
                                                        ${sale.paymentMethod === "CASH"
                                                                ? "bg-green-100 text-green-700"
                                                                : "bg-blue-100 text-blue-700"
                                                            }`}
                                                    >
                                                        {sale.paymentMethod}
                                                    </span>

                                                </div>

                                                <p className="text-sm text-gray-600 mt-1">
                                                    Sold By: {sale.cashierName}
                                                </p>

                                            </div>

                                            <div className="text-right">

                                                <p className="text-sm text-gray-600">
                                                    {formatDateTime(sale.createdAt)}
                                                </p>

                                                <p className="font-bold">
                                                    Total: KES {sale.totalAmount}
                                                </p>

                                            </div>

                                        </div>

                                    </div>

                                    {/* ITEMS TABLE */}
                                    <table className="w-full border-collapse">

                                        <thead>

                                            <tr className="bg-blue-50">

                                                <th className="border p-2 text-left">
                                                    Product
                                                </th>

                                                <th className="border p-2">
                                                    Qty
                                                </th>

                                                <th className="border p-2">
                                                    Price
                                                </th>

                                                <th className="border p-2">
                                                    Subtotal
                                                </th>

                                            </tr>

                                        </thead>

                                        <tbody>

                                            {sale.items.map((item) => (

                                                <tr key={item.id}>

                                                    <td className="border p-2">
                                                        {item.productName}
                                                    </td>

                                                    <td className="border p-2 text-center">
                                                        {item.quantity}
                                                    </td>

                                                    <td className="border p-2 text-center">
                                                        KES {item.price}
                                                    </td>

                                                    <td className="border p-2 text-center">
                                                        KES {item.subtotal}
                                                    </td>

                                                </tr>

                                            ))}

                                        </tbody>

                                    </table>

                                </div>

                            ))}

                        </div>

                    )}

                </div>

            </div>

            {/* FOOTER */}
            <div className="mt-4 flex justify-between">

                <button
                    onClick={() => navigate("/dashboard")}
                    className="bg-green-600 hover:bg-green-700 text-white px-6 py-3 rounded-lg"
                >
                    ⬅ Back to Dashboard
                </button>

            </div>

        </div>
    );
}

export default SalesReport;