import { useEffect, useState } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function TodaySales() {

    const [sales, setSales] = useState([]);

    const token = localStorage.getItem("token");

    let generatedBy = "Unknown User";

    if (token) {

        try {

            const payload = JSON.parse(
                atob(token.split(".")[1])
            );

            generatedBy = payload.sub;

        } catch (error) {
            console.error("Invalid token");
        }
    }

    useEffect(() => {
        fetchTodaySales();
    }, []);

    // =========================
    // FETCH SALES
    // =========================
    const fetchTodaySales = async () => {

        try {

            const response = await axios.get(
                "http://localhost:8080/api/sales/today",
                {
                    headers: {
                        Authorization: `Bearer ${token}`
                    }
                }
            );

            setSales(response.data);

        } catch (error) {
            console.error(error);
        }
    };

    // =========================
    // TOTALS
    // =========================
    const totalCash = sales
        .filter(
            s =>
                s.paymentMethod?.toLowerCase() === "cash"
        )
        .reduce(
            (sum, s) => sum + s.totalAmount,
            0
        );

    const totalMpesa = sales
        .filter(
            s =>
                s.paymentMethod?.toLowerCase() === "mpesa"
        )
        .reduce(
            (sum, s) => sum + s.totalAmount,
            0
        );

    const grandTotal = sales.reduce(
        (sum, s) => sum + s.totalAmount,
        0
    );

    // =========================
    // PDF DOWNLOAD
    // =========================
    const downloadPDF = () => {

        const doc = new jsPDF("landscape");

        doc.setFontSize(18);
        doc.text("TEL AVIV POS SYSTEM", 14, 20);

        doc.setFontSize(12);
        doc.text("Today's Sales Summary", 14, 30);

        doc.setFontSize(11);

        doc.text(
            `Generated By: ${generatedBy}`,
            14,
            45
        );

        doc.text(
            `Generated At: ${new Date().toLocaleString()}`,
            14,
            53
        );

        doc.setFont("helvetica", "bold");

        doc.text(
            `Cash: Ksh ${totalCash.toLocaleString()}`,
            220,
            45
        );

        doc.text(
            `MPESA: Ksh ${totalMpesa.toLocaleString()}`,
            220,
            53
        );

        doc.text(
            `Grand: Ksh ${grandTotal.toLocaleString()}`,
            220,
            61
        );

        doc.setFont("helvetica", "normal");

        const tableRows = [];

        sales.forEach((sale) => {

            sale.items.forEach((item) => {

                tableRows.push([
                    sale.id,
                    item.productName,
                    item.quantity,
                    `Ksh ${item.price}`,
                    `Ksh ${item.subtotal}`,
                    sale.paymentMethod,
                    sale.cashierName,
                    new Date(sale.createdAt)
                        .toLocaleString()
                ]);

            });

        });

        autoTable(doc, {

            startY: 75,

            head: [[
                "Sale ID",
                "Product",
                "Qty",
                "Price",
                "Subtotal",
                "Payment",
                "Cashier",
                "Date & Time"
            ]],

            body: tableRows

        });

        const pageHeight =
            doc.internal.pageSize.height;

        doc.text(
            `Summary generated by ${generatedBy}`,
            14,
            pageHeight - 10
        );

        doc.save("today-sales-summary.pdf");
    };

    const handleReprintReceipt = (sale) => {
        try {

            if (!sale) {
                alert("No sale selected");
                return;
            }

            const printWindow = window.open("", "_blank");

            if (!printWindow) {
                alert("Popup blocked. Please allow popups.");
                return;
            }

            const items = sale.items || [];

            const html = `
            <!DOCTYPE html>
            <html>
            <head>
                <title>Receipt #${sale.id}</title>
                <style>
                    body {
                        font-family: Arial;
                        padding: 20px;
                    }
                    h2 {
                        text-align: center;
                    }
                    table {
                        width: 100%;
                        border-collapse: collapse;
                        margin-top: 20px;
                    }
                    th, td {
                        border: 1px solid #000;
                        padding: 8px;
                    }
                </style>
            </head>

            <body>

                <h2>TEL AVIV POS RECEIPT</h2>

                <p><b>Sale ID:</b> ${sale.id || "N/A"}</p>
                <p><b>Cashier:</b> ${sale.cashierName || "Unknown"}</p>
                <p><b>Payment:</b> ${sale.paymentMethod || "N/A"}</p>
                <p><b>Date:</b> ${sale.createdAt ? new Date(sale.createdAt).toLocaleString() : "N/A"}</p>

                <table>
                    <thead>
                        <tr>
                            <th>Product</th>
                            <th>Qty</th>
                            <th>Price</th>
                            <th>Subtotal</th>
                        </tr>
                    </thead>

                    <tbody>
                        ${items.length > 0 ? items.map(item => `
                            <tr>
                                <td>${item.productName}</td>
                                <td>${item.quantity}</td>
                                <td>Ksh ${item.price}</td>
                                <td>Ksh ${item.subtotal}</td>
                            </tr>
                        `).join("") : `
                            <tr>
                                <td colspan="4" style="text-align:center;">
                                    No items found
                                </td>
                            </tr>
                        `}
                    </tbody>
                </table>

                <h3 style="text-align:right;margin-top:20px;">
                    TOTAL: Ksh ${(sale.totalAmount || 0).toLocaleString()}
                </h3>

            </body>
            </html>
        `;

            printWindow.document.open();
            printWindow.document.write(html);
            printWindow.document.close();

            setTimeout(() => {
                printWindow.focus();
                printWindow.print();
            }, 300);

        } catch (error) {
            console.error("Reprint failed:", error);
            alert("Could not reprint receipt");
        }
    };

    return (

        <div className="p-6 bg-gray-100 min-h-screen flex flex-col">

            {/* HEADER */}
            <h1 className="text-3xl font-bold text-gray-800 mb-6">
                📅 Today's Sales
            </h1>

            {/* TOTAL CARDS */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">

                <div className="bg-green-600 text-white p-6 rounded-2xl shadow-lg">

                    <h2 className="text-lg font-semibold mb-2">
                        💵 Cash Total
                    </h2>

                    <p className="text-3xl font-bold">
                        Ksh {totalCash.toLocaleString()}
                    </p>

                </div>

                <div className="bg-blue-600 text-white p-6 rounded-2xl shadow-lg">

                    <h2 className="text-lg font-semibold mb-2">
                        📱 MPESA Total
                    </h2>

                    <p className="text-3xl font-bold">
                        Ksh {totalMpesa.toLocaleString()}
                    </p>

                </div>

                <div className="bg-amber-500 text-white p-6 rounded-2xl shadow-lg">

                    <h2 className="text-lg font-semibold mb-2">
                        🧾 Grand Total
                    </h2>

                    <p className="text-3xl font-bold">
                        Ksh {grandTotal.toLocaleString()}
                    </p>

                </div>

            </div>

            {/* ALL SALE ITEMS */}
            <div className="flex-1 bg-white rounded-2xl shadow-lg overflow-y-auto p-5">

                <h2 className="text-2xl font-bold mb-5">
                    All Sale Items
                </h2>

                {sales.length === 0 ? (

                    <p className="text-gray-500">
                        No items sold today
                    </p>

                ) : (

                    <div className="space-y-6">

                        {sales.map((sale) => (

                            <div
                                key={sale.id}
                                className="border rounded-2xl overflow-hidden"
                            >

                                {/* SALE HEADER */}
                                <div className="bg-gray-100 border-b p-4">

                                    <div className="flex justify-between flex-wrap">

                                        <div>

                                            <div className="flex items-center gap-3">

                                                <h3 className="font-bold text-lg">
                                                    Sale #{sale.id}
                                                </h3>

                                                <span
                                                    className={`px-3 py-1 rounded-full text-sm font-bold
                                                    ${sale.paymentMethod?.toLowerCase() === "cash"
                                                            ? "bg-green-100 text-green-700"
                                                            : "bg-blue-100 text-blue-700"
                                                        }`}
                                                >
                                                    {sale.paymentMethod}
                                                </span>

                                            </div>

                                            <p className="text-gray-600 mt-1">
                                                Cashier: {sale.cashierName}
                                            </p>

                                        </div>

                                        <div className="text-right">

                                            <p className="text-gray-600 text-sm">
                                                {new Date(sale.createdAt)
                                                    .toLocaleDateString()}
                                                {" | "}
                                                {new Date(sale.createdAt)
                                                    .toLocaleTimeString()}
                                            </p>

                                            <p className="font-bold text-green-700">
                                                Total:
                                                {" "}
                                                Ksh {sale.totalAmount.toLocaleString()}
                                            </p>

                                            {/* Reprint Receipt Button */}
                                            <button
                                                onClick={() => handleReprintReceipt(sale)}
                                                className="bg-gray-800 text-white px-4 py-2 rounded-xl shadow hover:bg-gray-700 transition"
                                            >
                                                🧾 Reprint Receipt
                                            </button>

                                        </div>


                                    </div>

                                </div>

                                {/* ITEMS TABLE */}
                                <table className="w-full border-collapse">

                                    <thead>

                                        <tr className="bg-blue-50">

                                            <th className="border p-3 text-left">
                                                Product
                                            </th>

                                            <th className="border p-3">
                                                Qty
                                            </th>

                                            <th className="border p-3">
                                                Price
                                            </th>

                                            <th className="border p-3">
                                                Subtotal
                                            </th>

                                            <th className="border p-3">
                                                Payment
                                            </th>

                                        </tr>

                                    </thead>

                                    <tbody>

                                        {sale.items.map((item) => (

                                            <tr
                                                key={item.id}
                                                className="hover:bg-gray-50"
                                            >

                                                <td className="border p-3">
                                                    {item.productName}
                                                </td>

                                                <td className="border p-3 text-center">
                                                    {item.quantity}
                                                </td>

                                                <td className="border p-3 text-center">
                                                    Ksh {item.price}
                                                </td>

                                                <td className="border p-3 text-center font-semibold">
                                                    Ksh {item.subtotal}
                                                </td>

                                                <td className="border p-3 text-center">

                                                    <span
                                                        className={`px-3 py-1 rounded-full text-sm font-bold
                                                        ${sale.paymentMethod?.toLowerCase() === "cash"
                                                                ? "bg-green-100 text-green-700"
                                                                : "bg-blue-100 text-blue-700"
                                                            }`}
                                                    >
                                                        {sale.paymentMethod}
                                                    </span>

                                                </td>

                                            </tr>

                                        ))}

                                    </tbody>

                                </table>

                            </div>

                        ))}

                    </div>

                )}

            </div>

            {/* ACTION BAR */}
            <div className="mt-6 flex items-center justify-between">

                {/* LEFT SPACE */}
                <div className="w-1/3"></div>

                {/* CENTER */}
                <div className="w-1/3 flex justify-center">

                    <button
                        onClick={() =>
                            window.location.href =
                            "/dashboard"
                        }
                        className="bg-gray-600 hover:bg-gray-700 text-white px-6 py-3 rounded-xl shadow-lg transition"
                    >
                        ← Back to Dashboard
                    </button>

                </div>

                {/* RIGHT */}
                <div className="w-1/3 flex justify-end">

                    <button
                        onClick={downloadPDF}
                        className="bg-red-600 hover:bg-red-700 text-white px-6 py-3 rounded-xl shadow-lg transition"
                    >
                        📥 Download Sales Summary
                    </button>

                </div>

            </div>

        </div>
    );
}export default TodaySales;